- name: Check if there's cvechecker executable already
  stat:
    path: /usr/local/bin/cvereport
  register: stat_result
- name: build and install cvechecker executable
  include_tasks: build.yml
  when: not stat_result.stat.exists
- name: create cve checker scripts
  template:
    src: checkCVE.sh.j2
    dest: /usr/local/bin/checkCVE.sh
    owner: root
    group: root
    mode: '700'
- name: install mailutils
  apt:
    name: mailutils
    update_cache: yes
- name: setup cron for cve checker
  cron:
    name: "CVE Checker weekly setup"
    minute: 0
    hour: 1
    day: '*'
    month: '*'
    weekday: 0
    job: "/usr/bin/ionice -c3 /usr/local/bin/checkCVE.sh"